//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Ninja.Sha!4H")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("2023")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(".Net library to generate signed SAML 2.0 Response.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.5")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.5")]
[assembly: System.Reflection.AssemblyProductAttribute("Secure.SAML")]
[assembly: System.Reflection.AssemblyTitleAttribute("Secure.SAML")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.5")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/NinjaRocks/Secure.SAML")]
// Generated by the MSBuild WriteCodeFragment class.

